services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik.loadBalancer.server.port=8080
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme.json:/acme.json:rw
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: false
