services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: false
