services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - "--certificatesresolvers.cloudflare.acme.email=${EMAIL}"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme.json:/acme.json:rw
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - EMAIL=${EMAIL}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: false
